# Generated by Django 5.0.1 on 2024-02-02 21:48

import django.db.models.deletion
import django.db.models.fields
import main.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadiums',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('per_address', models.CharField(max_length=255)),
                ('contact_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('owner', models.ForeignKey(limit_choices_to={'user_roles': 'STADIUM_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='stadiums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stadiums',
            },
        ),
        migrations.CreateModel(
            name='StadiumsPictures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=main.utils.slugify_upload)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.fields.CharField, related_name='images', to='main.stadiums')),
            ],
            options={
                'db_table': 'stadium_pictures',
            },
        ),
    ]
